NSLoger/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'NSLoger.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^$', views.index),
    #url(r'^subject/(?P<subject_id>\d)/$', views.subject, name='subject'),
    #url(r'^user/(?P<user_id>\d)/$', views.user, name="user"),
    #url(r'^login/', views.login),
    #url(r'^register/', views.register),
    #url(r'^logout/', views.logout),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('bbs.urls', namespace='bbs')),
    url(r'^sites/', include('sites.urls', namespace='sites')),
    url(r'^', include('people.urls', namespace='user')),
    url(r'^', include('page.urls', namespace='page')),
)

bbs/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from bbs import views


urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^recent/?$',views.recent, name='recent'),
        url(r'^t/(?P<topic_id>\d+)/$', views.topic, name="topic"),
        url(r'^t/(\d+)/reply/?$',views.reply,name='reply'),
        url(r'^t/(\d+)/edit/?$',views.edit,name='edit'),
        url(r'^t/fav/(?P<topic_id>\d+)/$', views.fav_topic, name="fav_topic"),
        url(r'^t/unfav/(?P<topic_id>\d+)/$', views.unfav_topic, name="unfav_topic"),
        url(r'^node/([\w-]+)/new/?$',views.new,name='new'),
        url(r'^node/(?P<node_slug>[\w-]+)/$',views.node,name="node"),
	url(r'^notice/?$',views.notice,name='notice'),
	url(r'^notice/(\d+)/delete/?$',views.notice_delete,name='notice_delete'),
        )

people/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

from people import views
import bbs

urlpatterns = patterns('',
        url(r'^register/$', views.register, name="register"),
        url(r'^login/$', views.login, name="login"),
        url(r'^logout/$', views.logout, name="logout"),
        url(r'^settings/$', views.profile, name="settings"),
        url(r'^settings/upload_headimage/$', views.upload_headimage, name="upload_headimage"),
        url(r'^settings/delete_headimage/$', views.delete_headimage, name="delete_headimage"),
        url(r'^password/$', views.password, name="password"),
        url(r'^user/(?P<uid>\d+)/$', views.user, name="user"),
        url(r'^user/(?P<uid>\d+)/topics/$', views.user_topics, name="user_topics"),
        url(r'^user/(?P<uid>\d+)/comments/$', views.user_comments, name="user_comments"),
        url(r'^users/$', views.au_top, name="au_top"),
        url(r'^follow/(?P<uid>\d+)/$', views.follow, name="follow"),
        url(r'^unfollow/(?P<uid>\d+)/$', views.un_follow, name="unfollow"),
        url(r'^my/following/$', views.following, name="following"),
        url(r'^my/fav/$', bbs.views.fav_topic_list, name="faved_topic_list"),
        url(r'^send_verified_email/$', views.send_verified_email, name="send_verified_email"),
        url(r'^email_verified/(?P<uid>\d+)/(?P<token>\w+)/$', views.email_verified, name="email_verified"),
        url(r'^find_password/$', views.find_password, name="find_pass"),
        url(r'^reset_password/(?P<uid>\d+)/(?P<token>\w+)/$', views.first_reset_password, name="first_reset_password"),
        url(r'^reset_password/$', views.reset_password, name="reset_password"),
        )

bbs/forms.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
from django import forms
from bbs.models import Topic, Comment

class TopicForm(forms.ModelForm):
    title = forms.CharField(label=u'标题',required=True)
    content = forms.CharField(label=u'内容',required=False)

    def clean_title(self):
        title = self.cleaned_data.get("title").strip()
        #if len(title) == 0:
            #raise forms.ValidationError("请输入标题...")
        if len(title) < 3:
            raise forms.ValidationError("标题太短哦...")
        elif len(title) > 100:
            raise forms.ValidationError("标题太长哦...")
        else:
            return title

    def clean_content(self):
        content = self.cleaned_data.get("content").strip()
        #if len(content) == 0:
            #raise forms.ValidationError("请输入内容...")
        #elif len(content) < 10:
            #raise forms.ValidationError("正文内容太短哦...")
        if len(content) > 5000:
            raise forms.ValidationError("正文内容太长哦...")
        else:
            return content

    class Meta:
        model = Topic
        fields = ('title','content')


class ReplyForm(forms.ModelForm):
    content = forms.CharField(label=u'回复',required=False)

    def clean_content(self):
        content = self.cleaned_data.get("content").strip()
        if len(content) == 0:
            raise forms.ValidationError("请输入评论内容...")
        #elif len(content) < 5:
            #raise forms.ValidationError("评论内容太短哦...")
        elif len(content) > 800:
            raise forms.ValidationError("评论内容太长哦...")
        else:
            return content

    class Meta:
        model = Comment
        fields = ('content',)

class EditForm(forms.Form):
    content = forms.CharField(label=u'内容',max_length=1000,widget=forms.Textarea(attrs={'class':'form-control','rows':'20'}))

bbs/views.py
# -*- coding: utf-8 -*-
import re
from django.shortcuts import render_to_response,render,HttpResponseRedirect
from django.http import Http404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.core.cache import cache

from models import Topic,Comment,Category,Node,Notice, FavoritedTopic
from people.models import Member as User
from bbs.forms import ReplyForm, TopicForm, EditForm
from django.db import IntegrityError

from django.contrib import messages
from NSLoger.settings import NUM_TOPICS_PER_PAGE,NUM_COMMENT_PER_PAGE

import datetime
from django.db.models import Count 

def index(request):
    '''首页'''

    # 主题列表
    topic_list = Topic.objects.all().order_by('-updated_on')[:NUM_TOPICS_PER_PAGE]

    # 节点导航
    nodes = cache.get('index_nodes')  #取缓存
    if not nodes:
        nodes = []
        categor_list = Category.objects.all()
        print request.path
        for category in categor_list:
            node = {}
            category_nodes = Node.objects.filter(category=category.id)
            node['category_name'] = category.name
            node['category_nodes'] = category_nodes
            nodes.append(node)
        cache.set('index_nodes',nodes,600); #10分钟刷新

    
    # 今日热议
    hot_topics = cache.get('index_hot_topics')  #取缓存
    if not hot_topics:
        now = timezone.now()
        start = now - datetime.timedelta(hours=23, minutes=59, seconds=59)
        hot_comments = Comment.objects.filter(created_on__gt=start).values('topic').annotate(count=Count('topic')).order_by('-count')[:10]
        hot_topics = []
        for comment in hot_comments:
            topic = Topic.objects.get(id=comment['topic'])
            hot_topics.append(topic)
        cache.set('index_hot_topics',hot_topics,300); #5分钟刷新

    return render(request,"bbs/index.html",{
        'topic_list':topic_list,
        'nodes':nodes,  
        'hot_topics':hot_topics
        })

def recent(request):
    topic_list = Topic.objects.all().order_by('-created_on')
    paginator = Paginator(topic_list, NUM_TOPICS_PER_PAGE)
    page = request.GET.get('page')

    try:
        topic_list = paginator.page(page)
    except PageNotAnInteger:
        topic_list = paginator.page(1)
    except EmptyPage:
        topic_list = paginator.page(paginator.num_pages)

    return render(request,"bbs/recent.html",{"topic_list":topic_list});

def topic(request,topic_id):
    '''主题详情'''

    try:
        topic = Topic.objects.get(id=topic_id)
    except Topic.DoesNotExist:
        raise Http404

    topic.num_views += 1
    topic.save()

    faved_num = FavoritedTopic.objects.filter(topic=topic).count()

    if request.user.is_authenticated():
        try:
            faved_topic = FavoritedTopic.objects.filter(user=request.user, topic=topic).first()
        except (User.DoesNotExist, FavoritedTopic.DoesNotExist):
            faved_topic = None

    # Comment
    comment_list = Comment.objects.filter(topic=topic).order_by('created_on')
    paginator = Paginator(comment_list, NUM_COMMENT_PER_PAGE)
    page = request.GET.get('page')
    if page == None:
        page = paginator.num_pages

    try:
        comment_list = paginator.page(page)
    except PageNotAnInteger:
        comment_list = paginator.page(1)
    except EmptyPage:
        comment_list = paginator.page(paginator.num_pages)

    form = ReplyForm()
    return render(request,"bbs/topic.html", locals())

@login_required
def reply(request, topic_id):

    try:
        topic = Topic.objects.get(id=topic_id)
        # comment ---
        comment_list = Comment.objects.filter(topic=topic).order_by('created_on')
        paginator = Paginator(comment_list, NUM_COMMENT_PER_PAGE)
        page = request.GET.get('page')
        if page == None:
            page = paginator.num_pages

        try:
            comment_list = paginator.page(page)
        except PageNotAnInteger:
            comment_list = paginator.page(1)
        except EmptyPage:
            comment_list = paginator.page(paginator.num_pages)
        # comment ---
    except Topic.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            last_comment = Comment.objects.filter(author=request.user).order_by('-created_on')[:1]
            last_comment = last_comment.first()
            if last_comment and last_comment.content == form.clean()['content'] and ((timezone.now()-last_comment.created_on).seconds < 10):
                messages.error(request,'你是否正在尝试连续提交两次相同的回复？');
            else:
                comment = form.save(commit=False)
                request.user.comment_num += 1
                request.user.calculate_au()
                request.user.save()
                comment.author = request.user

                try:
                    topic = Topic.objects.get(id=topic_id)
                except Topic.DoesNotExist:
                    raise Http404

                comment.topic = topic
                comment.save()

                # --- 解析@ ---

                #team_name_pattern = re.compile('(?<=@)(\w+)', re.UNICODE)
                team_name_pattern = re.compile('(?<=@)([0-9a-zA-Z_.]+)', re.UNICODE)
                at_name_list = set(re.findall(team_name_pattern, comment.content))
                if at_name_list:
                    for at_name in at_name_list:
                        if at_name != comment.author.username and at_name != comment.topic.author.username:
                            try:
                                at_user = User.objects.get(username=at_name)
                                if at_user:
                                    notice = Notice(from_user=comment.author,to_user=at_user    ,topic=comment.topic,content=comment.content)
                                    notice.save()
                            except:
                                pass

                # --- 解析@ ---

                topic.num_comments += 1
                topic.updated_on = timezone.now()
                topic.last_reply = request.user
                topic.save()
                return HttpResponseRedirect(reverse("bbs:topic" ,args=(topic_id,)))
    else:
        form = ReplyForm()

    return render(request,"bbs/topic.html",{"node":node,"topic":topic,"form":form,"comment_list":comment_list,'paginator':paginator})


def node(request, node_slug):
    '''节点页'''

    try:
        node = Node.objects.get(slug=node_slug)
    except Node.DoesNotExist:
        raise Http404

    topic_list = Topic.objects.filter(node=node).order_by('-created_on')
    paginator = Paginator(topic_list, NUM_TOPICS_PER_PAGE)
    page = request.GET.get('page')

    try:
        topic_list = paginator.page(page)
    except PageNotAnInteger:
        topic_list = paginator.page(1)
    except EmptyPage:
        topic_list = paginator.page(paginator.num_pages)

    return render(request,"bbs/node.html",{"node":node, "topic_list":topic_list})

@login_required
def new(request, node_slug):
    context = {}
    try:
        node = Node.objects.get(slug=node_slug)
    except Node.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            last_topic = Topic.objects.filter(author=request.user).order_by('-created_on')[:1]
            last_topic = last_topic.first()
            if last_topic and last_topic.title == form.clean()['title'] and ((timezone.now()-last_topic.created_on).seconds < 10):
                messages.error(request,'你是否正在尝试连续提交两次相同的内容？');
                return HttpResponseRedirect(reverse("bbs:topic" ,args=(last_topic.id,)))
            else:
                topic = form.save(commit=False)
                topic.node = node
                request.user.topic_num += 1
                request.user.calculate_au()
                request.user.save()
                topic.author = request.user
                topic.last_reply = request.user
                topic.updated_on = timezone.now()
                topic.save()
                node.num_topics += 1
                node.save()

                # --- 解析@ ---

                team_name_pattern = re.compile('(?<=@)(\w+)', re.UNICODE)
                at_name_list = set(re.findall(team_name_pattern, topic.content))
                if at_name_list:
                    for at_name in at_name_list:
                        if at_name != topic.author.username:
                            try:
                                at_user = User.objects.get(username=at_name)
                                if at_user:
                                    notice = Notice(from_user=topic.author,to_user=at_user,topic=topic,content='')
                                    notice.save()
                            except:
                                pass

                # --- 解析@ ---

                return HttpResponseRedirect(reverse("bbs:topic" ,args=(topic.id,)))
    else:
        form = TopicForm()

    return render(request,'bbs/new.html',{'node':node,'form':form})

@login_required
def edit(request,topic_id):

    try:
        topic = Topic.objects.get(id=topic_id)
        if topic.author != request.user:
            raise Http404
    except Node.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            topic.title = form.clean()['title']
            topic.content = form.clean()['content']
            topic.updated_on = timezone.now()
            topic.save()
            return HttpResponseRedirect(reverse("bbs:topic" ,args=(topic.id,)))
    else:
        form = TopicForm(instance=topic)
    
    return render(request,'bbs/edit.html',{'topic':topic,'form':form})

@login_required
def notice(request):
    context = {}
    if request.method == 'GET':

templates/bbs/edit.html
{% extends "base.html" %}
{% block title %}主题编辑 - {% endblock %}
{% block content %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <ol class="breadcrumb">
                        <li><a href="/">首页</a></li>
                        <li><a href="{% url 'bbs:node' topic.node.slug %}">{{topic.node.name}}</a></li>
                        <li><a href="{% url 'bbs:topic' topic.id %}">{{topic.title}}</a></li>
                        <li>编辑</li>
                    </ol>
                </div>
                <div class="panel-body">
                    {% if form.title.errors or form.content.errors %}
                    <div>
                        <ol class="alert alert-danger">
                        遇到问题了：
                        {% for field in form %}
                          {% for error in field.errors %}
                            <li style="margin-left:30px;">{{ error }}</li>
                          {% endfor %}
                        {% endfor %}
                        </ol>
                    </div>
                    {% endif %}
                    <form role="form" action="{% url 'bbs:edit' topic.id %}" method="post" class="form-vertical">
                      {% csrf_token %}

                      <div class="form-group">
                        <label >{{ form.title.label }}:</label>
                        <input type="text" class="form-control" name="{{ form.title.html_name }}" value="{{ form.title.value |default_if_none:""}}">
                      </div>
                      <div class="form-group">
                        <label>{{ form.content.label }}:</label>
                          <textarea name="content" id="content" class="form-control" rows="10">{{ form.content.value |default_if_none:""}}</textarea>
                      </div>

                      <button type="submit" class="btn btn-default" data-loading-text="正在提交...">编辑</button>
                    </form>
                  </div>
                </br>
                  <blockquote>
                    <small>你可以使用Markdown语法</small>
                  </blockquote>
              </div>
{% endblock %}

{% block sidebar %}
<div class="panel panel-default">
    <div class="panel-heading">Markdown 快速参考</div>
    <div class="panel-body">
      <ul>
        <li>http://example.org 自动加链接</li>
        <li>**粗体**</li>
        <li>~~删除线~~、</li>
        <li>`单行代码`</li>
        <li>```多行代码```</li>
        <li>![图片 Alt text](http://url.com/img.jpg)</li>
      </ul>
    </div>
</div>
{% endblock %}

templates/bbs/fav_topic.html
{% extends "base.html" %}

{% block title %}收藏列表 - {% endblock %}

{% load bbstag %}
{% load gravatar %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">收藏列表</div>
    <div class="panel-body tableview">
        {% for faved in faved_topic %}
                      <div class="cell">
                          <div class="pull-left">
                              <a href="{% url 'user:user' faved.topic.author.id %}" title="{{ faved.topic.author }}">
                                  <img width="48" height="48" class="headimage" src="{% gravatar faved.topic.author 48 %}">
                              </a>
                          </div>
                          <div class="detail">
                              <div class="pull-right">
                                  <div class="badge badge-info">
                                      <a href="{% url 'bbs:topic' faved.topic.id %}">
                                          {{ faved.topic.num_comments }}
                                      </a>
                                  </div>
                              </div>
                              <a href="{% url 'bbs:topic' faved.topic.id %}" class="title">
                                  {{faved.topic.title}}
                              </a>
                              <div class="meta">
                                  <a href="{% url 'bbs:node' faved.topic.node.slug %}" class="node">
                                      {{ faved.topic.node.name }}
                                  </a>
                                  <span class="text-muted">
                                      •
                                  </span>
                                  <a href="{% url 'user:user' faved.topic.author.id %}" title="{{ faved.topic.author }}">
                                      {{ faved.topic.author }}
                                  </a>
                                  <span class="text-muted">
                                      •
                                  </span>
                                  {{ faved.topic.created_on|time_to_now }}
                                  <span class="text-muted">
                                      •
                                  </span>
                                  最后回复来自
                                  <a href="{% url 'user:user' faved.topic.last_reply.id %}"  title="{{ faved.topic.last_reply }}">
                                      {{ faved.topic.last_reply }}  
                                  </a>
                              </div>
                          </div>
                      </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/bbs/index.html
{% extends "base.html" %}

{% load gravatar %}
{% load cache %}

{% block content %}

<div class="panel panel-default">
  <div class="panel-heading">Cocoa开发者的聚集地</div>
  <div class="panel-body tableview">
    {% cache 30 sidebar index_topics %}
    {% for topic in topic_list %}
        {% include "bbs/topic_cell.html" %}
    {% endfor %}
    {% endcache %}
  </div>
  <div class="panel-body">
    <ul class="pager">
      <li class="next"><a href="{% url 'bbs:recent' %}">更多话题</a></li>
    </ul>
  </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">节点导航</div>
    <div class="panel-body node-panel">  
        <ul>
        {% for item in nodes %}
          <li>
            <div class="row text-muted node-line">
                <div class="col-xs-4 col-sm-3 col-md-2 category-name">{{item.category_name}}</div>
                <div class="col-xs-8 col-sm-9 col-md-10">
                  {% for node in item.category_nodes %}
                        <a class="node-name" href="/node/{{node.slug}}">{{ node.name }}</a>
                    {% endfor %}  
                </div>
              </div>
          </li>
          {% endfor %}
      </ul>
    </div>
</div>

{% endblock %}

{% block sidebar %}

<div class="panel panel-default hidden-xs">
  <div class="panel-heading">今日热议</div>
  <div class="panel-body tableview">
      {% for topic in hot_topics %}
        <div class="cell">
        <table cellpadding="0" cellspacing="0" border="0" width="100%">
            <tbody><tr>
                <td width="24" valign="middle" align="center">
                    <a href="{% url 'user:user' topic.author.id %}"><img src="{% gravatar topic.author 48 %}" class="avatar" border="0" align="default" style="max-width: 24px; max-height: 24px;"></a>
                </td>
                <td width="10"></td>
                <td width="auto" valign="middle">
                  <span>
                    <a href="{% url 'bbs:topic' topic.id %}">{{topic.title}}</a>
                  </span>
                </td>
            </tr>
        </tbody></table>
        </div>
      {% endfor %}
  </div>
</div>

{% endblock %}

templates/bbs/new.html
{% extends "base.html" %}
{% block title %}新主题 - {% endblock %}
{% block content %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <ol class="breadcrumb">
                        <li><a href="/">首页</a></li>
                        <li><a href="{% url 'bbs:node' node.slug %}">{{node.name}}</a></li>
                        <li>新主题</li>
                    </ol>
                </div>
                <div class="panel-body">
                    {% if form.title.errors or form.content.errors %}
                    <div>
                        <ol class="alert alert-danger">
                        遇到问题了：
                        {% for field in form %}
                          {% for error in field.errors %}
                            <li style="margin-left:30px;">{{ error }}</li>
                          {% endfor %}
                        {% endfor %}
                        </ol>
                    </div>
                    {% endif %}
                    <form role="form" action="{% url 'bbs:new' node.slug %}" method="post" class="form-vertical">
                      {% csrf_token %}

                      <div class="form-group">
                        <label >{{ form.title.label }}:</label>
                        <input type="text" class="form-control" name="{{ form.title.html_name }}" value="{{ form.title.value |default_if_none:""}}">
                      </div>
                      <div class="form-group">
                        <label>{{ form.content.label }}:</label>
                          <textarea name="content" id="content" class="form-control" rows="10">{{ form.content.value |default_if_none:""}}</textarea>
                      </div>

                      <button type="submit" class="btn btn-default" data-loading-text="正在提交...">发布</button>
                    </form>
                  </div>
                </br>
                  <blockquote>
                    <p>简明释义</p>
                    <small>我们鼓励分享、讨论、发表你的任何观点</small>
                    <small>支持Markdown语法</small>
                  </blockquote>
              </div>
{% endblock %}

{% block sidebar %}
<div class="panel panel-default">
    <div class="panel-heading">Markdown 快速参考</div>
    <div class="panel-body">
      <ul>
        <li>http://example.org 自动加链接</li>
        <li>**粗体**</li>
        <li>~~删除线~~、</li>
        <li>`单行代码`</li>
        <li>```多行代码```</li>
        <li>![图片 Alt text](http://url.com/img.jpg)</li>
      </ul>
    </div>
</div>
{% endblock %}

templates/bbs/topic.html
{% extends "base.html" %}

{% block title %}{{ topic.title }} - {% endblock %}

{% load gravatar %}
{% load bbstag %}

{% block content %}
<div class="panel panel-default">
                  <div class="topic-header">
                    <div class="topic-headimg pull-right"><a href="{% url 'user:user' topic.author.id %}"><img height="48" width="48" src="{% gravatar topic.author 48 %}" /></a></div>
                    <div class="topic_breadcrumb">
                        <a href="/">NSLoger</a>  ›   <a href="{% url 'bbs:node' topic.node.slug %}">{{ topic.node }}</a>
                    </div>
                    <div class="topic-title">{{ topic.title }}</div>
                    <div class="topic-meta text-muted">
                      By <a href="{% url 'user:user' topic.author.id %}">{{ topic.author.username }}</a> · {{ topic.created_on|time_to_now }} · {{ topic.num_views }} 次点击 · {{ faved_num }} 人收藏
                      {% if user.is_authenticated %}{% if user.id == topic.author.id %}
                       · <a href="{% url 'bbs:edit' topic.id %}" class="node">编辑</a>
                       {% endif %}{% endif %}
                    </div>
                  </div>
    <div class="panel-body">
      {{ topic.content|my_markdown:"topic" }}
    </div>

    <div class="panel-footer topic-footer">
    {% if user.is_authenticated %}
      {% if user.id != topic.author.id %}
      <div class="pull-left">
        {% if not faved_topic %}
          <form action="{% url 'bbs:fav_topic' topic.id %}" method="POST">
                      {% csrf_token %}
              <button class="btn btn-default fav-btn" type="submit">加入收藏</button>
          </form>
        {% else %}
          <form action="{% url 'bbs:unfav_topic' topic.id %}" method="POST">
                      {% csrf_token %}
              <button class="btn btn-default fav-btn" type="submit">取消收藏</button>
          </form>
        {% endif %}
      </div>
      {% endif %}
    {% endif %}
    <!-- Share -->
    <div class="pull-right">
      <div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more"></a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a><a href="#" class="bds_twi" data-cmd="twi" title="分享到Twitter"></a><a href="#" class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a><a href="#" class="bds_copy" data-cmd="copy" title="分享到复制网址"></a></div>
    </div>
    <div class="clearfix"></div>
    <!-- Share -->
    </div>
</div>

{% endblock %}


{% block reply %}
<div class="panel panel-default">
  <div class="panel-heading">{{ comment_list.count }} 回复</div>
  <div class="panel-body comment-tableview">
    {% for comment in comment_list %}
      {% include "bbs/topic_comments_cell.html" %}
    {% endfor %}
  </div>  
  {% if comment_list.paginator.num_pages > 1 %}
    <div class="panel-footer">
      <ul class="pager text-muted">

        {% if comment_list.has_previous %}
          <li class="previous">
            <a href="?page={{ comment_list.previous_page_number }}">&larr;上一页</a>
          </li>
        {% else %}
          <li class="previous disabled">
            <a href="#">&larr;上一页</a>
          </li>
        {% endif %}

        <li>{{ comment_list.number }}/{{ comment_list.paginator.num_pages }}</li>

        {% if comment_list.has_next %}
          <li class="next">
            <a href="?page={{ comment_list.next_page_number }}">下一页 &rarr;</a>
          </li>
        {% else %}
          <li class="next disabled">
            <a href="#">下一页 &rarr;</a>
          </li>
        {% endif %}
      </ul>
    </div>
  {% endif %}
</div>

{% if user.is_authenticated %}
  <div class="panel panel-default">
    <div class="panel-heading">回复</div>
    <div class="panel-body">
              <form class="text" action="{% url 'bbs:reply' topic.id %}" method="post">
                {% csrf_token %}

                <div class="form-group">
                  <label class="sr-only" for="replay">回复</label>
                  <textarea name="content" id="reply_content" class="form-control" rows="5">{{ form.content.value |default_if_none:""}}</textarea>
                </div>

                <button type="submit" class="btn btn-default submit-btn" data-loading-text="正在提交...">回复</button>

                {% if form.content.errors %}
                <label class="pull-right">
                  <ul class="list-inline">
                  {% for item in form.content.errors %}
                      <li><p class="form-control-static text-danger">{{ item }}</p></li>
                  {% endfor %}
                  </ul>
                </label>
                {% endif %}

              </form>
    </div>
  </div>
{% endif %}

{% endblock %}

{% block footer%}
<script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"1","bdSize":"16"},"share":{}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>
{% endblock %}

templates/bbs/topic_comments_cell.html
{% load gravatar %}
{% load bbstag %}
<div class="comment" id="comment{% page_item_idx paginator comment_list.number forloop %}">
  <table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody><tr>
  <td valign="top" width="48">
  <a href="{% url 'user:user' comment.author.id %}" title="{{ comment.author.username }}">
    <img height="48" width="48" src="{% gravatar comment.author 48 %}">
  </a>
  </td>
  <td width="10"></td>
  <td valign="top" width="auto">
    {% if user.is_authenticated %}
    <div class="pull-right">
      <span class="text-muted">
        <a href="#reply_content" onclick="replyOne('{{comment.author}}','{{forloop.counter}}');">回复</a>
      </span>
    </div>
    {% endif %}
    <div>{{forloop.counter|length }}
      <span class="name"><a href="{% url 'user:user' comment.author.id %}">{{ comment.author}}</a></span>
      <span class="datetime text-muted">{% page_item_idx paginator comment_list.number forloop %}楼 , {{ comment.created_on|time_to_now}}</span>
      <div class="content reply_content">{{ comment.content|my_markdown:"comment" }}</div>
    </div>
  </td>
  </tr>
  </tbody></table>
</div>